### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by Rudloff** [quai10/quai10-template#14]
Ça serait trop top cool d'avoir un sitemap.

**Comment by hiwelo** [comment]
On va passer via un système automatisé, voir avec Thomas si plutôt Yoast! ou autre ?

**Comment by Rudloff** [comment]
Tu veux que je fasse un sitemap.txt basique en attendant ?

**Comment by hiwelo** [comment]
Si tu es motivé, pourquoi pas :)

**Comment by Rudloff** [comment]
Voilà : https://quai10.org/sitemap.txt

**Comment by Rudloff** [comment]
Ayé, on a un vrai sitemap : https://quai10.org/sitemap.xml
