### ISSUE TITLE
Inclure les CSS compilés dans le dépot ?

### ISSUE THREAD

**Issue by Rudloff** [quai10/quai10-template#19]
Comme il faut compiler le tout avec Gulp, on est obligés de faire un hack dans le composer.json : https://github.com/quai10/quai10-wordpress/blob/master/composer.json#L78
C'est pas terrible et on pourrait peut être trouver une meilleure solution.

**Comment by Rudloff** [comment]
Le même problème se pose pour Bower, mais la solution semble être ça : https://github.com/francoispluchino/composer-asset-plugin

**Comment by hiwelo** [comment]
Perso je mets systématiquement `|| true` en fin de commande npm & gulp si c'est la question :)

**Comment by Rudloff** [comment]
C'est pas ça qui m'embête, c'est de devoir mettre ces commandes dans le projet parent alors que ça concerne la dépendance.
(Mais Composer compte pas gérer ça : https://github.com/composer/composer/issues/1193)

**Comment by hiwelo** [comment]
et si tu installes la dépendance via un create-project ? :/ c'est plus sale qu'un require mais au moins ça lance le composer install :/

**Comment by Rudloff** [comment]
Mais tu peux pas la mettre à jour après, non ?

**Comment by hiwelo** [comment]
Oui effectivement.
Dans ce cas, autant faire un `git clone` via les scripts _composer_.

**Comment by Rudloff** [comment]
Autant garder la solution actuelle quoi...

**Comment by hiwelo** [comment]
Bah ce n'est pas ça la solution actuelle ?

**Comment by Rudloff** [comment]
Ah je croyais que tu parlais de mettre un ```git clone``` à la main dans composer.json.

**Comment by Rudloff** [comment]
Bon vu que ni Composer, ni WordPress ne compte gérer ça correctement, le consensus actuel est d'integrer le CSS compilé dans le dépôt des thèmes pour faciliter leur distribution.
