### ISSUE TITLE
Plus de responsive

### ISSUE THREAD

**Issue by Rudloff** [quai10/quai10-template#20]
J'ai plus de responsive sur Chrome Android. Problème de meta viewport ?

**Comment by hiwelo** [comment]
Oui, la `meta viewport` n'a jamais été dé-commentée visiblement.
https://github.com/quai10/quai10-template/blob/master/header.php#L6

**Comment by Rudloff** [comment]
C'est corrigé : https://github.com/quai10/quai10-template/commit/c81b139e3eeb599c885652c1527d3c39f08132a4
