### ISSUE TITLE
Les placeholder du formulaire de contact sont trop clairs

### ISSUE THREAD

**Issue by Rudloff** [quai10/quai10-template#3]
Sur mon écran, les placeholders se voient à peine sur le fond blanc. Ça serait possible de les contraster un poil plus (accessibilité, toussa) ?

**Comment by hiwelo** [comment]
Je change ça ce soir.

**Comment by Rudloff** [comment]
J'ai déjà tagué la release que je met en ligne ce soir. On fera ça pour la prochaine mise à jour, c'est pas dramatique.
