### ISSUE TITLE
Page de lieu pas stylée

### ISSUE THREAD

**Issue by Rudloff** [quai10/quai10-template#37]
https://quai10.org/locations/labattoir-cafe/

**Comment by Rudloff** [comment]
@mr-am J'ai mis un style très basique: https://quai10.org/preprod/locations/quai-n10/
Est-ce que tu veux faire un peu plus.?

**Comment by mr-am** [comment]
Oui je pense on peut facilement faire un peu mieux en procédant comme pour single-event.php
Pourrais-tu m'envoyer la clé de l'API Google Map pour mon localhost, pour que je puisse afficher single-location.php et faire les tests ??

**Comment by Rudloff** [comment]
J'ai autorisé la clef d'API sur localhost.
Par contre maintenant j'ai cette erreur :
`Ce site a dépassé son quota journalier Google Maps`

**Comment by mr-am** [comment]
Sur mon localhost, j'ai ceci à la place de la carte :

> Petit problème... Une erreur s'est produite
Google Maps ne s'est pas chargé correctement sur cette page. Pour plus d'informations techniques sur cette erreur, veuillez consulter la console JavaScript.

Et dans la console JS, ceci :

> "Google Maps API error: RefererNotAllowedMapError https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: http://quai10/?event=evenement-1"  js:37:391
"Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version"

Et concernant ton message, peut-être  il y a un quota d'utilisation de la clé API apr unité de temps : du coup la même clé sur la prod, la préprod et nos localhost, avec les test qu'on fait, ça bloque. A confirmer néanmoins.

**Comment by Rudloff** [comment]
Ah mais ton domaine est pas `localhost` ?
Je dois autoriser chaque domaine un par un en fait. Je vais autoriser `quai10`.

**Comment by mr-am** [comment]
Oui je passe par un vhost

**Comment by Rudloff** [comment]
OK bah je viens d'autoriser `quai10` (ça met quelques minutes à se mettre à jour).

Concernant les quotas, il y a bien une limite par clef par jour mais on a de la marge :
![image](https://cloud.githubusercontent.com/assets/840125/22043367/92825ae8-dd0f-11e6-8bf7-c74f0b2216b7.png)
Par contre il y a aussi une limite par domaine et avec tous les gens qui utilisent `localhost` forcément...

**Comment by mr-am** [comment]
C'est bon ça marche !
Oui on a de la marge, la limite par DNS est plus contraignante  en effet...

**Comment by Rudloff** [comment]
@mr-am Il y avait encore des modifs à faire là-dessus ?

**Comment by mr-am** [comment]
Normalement non.
