### ISSUE TITLE
Remplacer Bower

### ISSUE THREAD

**Issue by Rudloff** [quai10/quai10-template#49]
Bower n'est plus maintenu : https://bower.io/blog/2017/how-to-migrate-away-from-bower/
Il faudrait migrer vers des paquets NPM/Yarn.

**Comment by mr-am** [comment]
Oui, en effet je l'ai lu il y a quelque temps.
Tu as un avis sur le choix du package manager du coup, npm vs yarn ?

**Comment by Rudloff** [comment]
Personnellement, je préfère Yarn mais de toute façon les deux utilisent le même fichier `package.json` donc chacun peut utiliser celui qu'il préfère.
Je vais faire une PR qui remplace les paquets Bower par des paquets NPM.
