### ISSUE TITLE
NetworkError: 404 Not Found - https://quai10.org/app/uploads/2015/08/background-train.png

### ISSUE THREAD

**Issue by Rudloff** [quai10/quai10-template#6]

**Comment by hiwelo** [comment]
C'est un background CTA géré via l'administration WordPress, ce n'est pas un soucis lié au template.

**Comment by Rudloff** [comment]
Je suppose que c'est un image que t'as ajouté en local et qui est pas sur le serveur. Tu pourras me la filer ?
